allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true

onlyBuiltDependencies:
  - unrs-resolver

patchedDependencies:
  prettier-plugin-astro: patches/prettier-plugin-astro.patch
