allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true

minimumReleaseAgeExclude:
  - '@types/react@19.2.15'
  - miniflare@4.20260518.0
  - wrangler@4.93.0

onlyBuiltDependencies:
  - unrs-resolver

patchedDependencies:
  prettier-plugin-astro: patches/prettier-plugin-astro.patch
