#!/usr/bin/env sh

handle_error() {
  echo "\033[0;31m\npre-commit hook failed\n\033[0m"
}
trap 'handle_error' ERR

echo "\033[0;34m\npre-commit hook started\033[0m"
echo "\033[0;34m\ninstalling dependencies...\n\033[0m"
npx pnpm install
echo "\033[0;34m\nrunning lint-staged...\n\033[0m"

npx pnpm typecheck
if [ $? -ne 0 ]; then
    exit 1
fi

npx lint-staged

echo "\033[0;32m\npre-commit hook passed\n\033[0m"
